### PR TITLE
Expose Client Fields

### PR DESCRIPTION
**Pull request by a-rustacean**
# Overview:

This PR aims to enhance the flexibility and usability of the `httpc-test` library by making the `cookie_store` and `client` fields on the `Client` struct publicly accessible.

## Changes Proposed:

1. **`Client` Struct Modification:**
   - The `cookie_store` field is made public to allow external access.
   - The `client` field is made public to facilitate its use in various tasks beyond the current scope of `httpc-test`.

## Benefits:

- Users of the library will have increased flexibility when working with the `Client` struct.
- This change aligns with the library's goal of improving extensibility and ease of use.

## Testing:

I have tested these changes to ensure they do not break existing functionality within the `httpc-test` library. Additionally, I've verified that the `cookie_store` and `client` fields are accessible as intended.

## Related Issues:

#13

### CODE REVIEW

**Comment by jeremychone** [comment]
@a-rustacean Thanks for the PR. It makes sense, and I concur that it aligns with the goal of convenience over "strictness."
I need to consider if there are any downsides to this.

What about exposing some methods that return `&Client` and `&ClientStore`? Just thinking out loud.

**Comment by a-rustacean** [comment]
OK, I've made the changes you suggested by adding two methods named `client` and `cookie_store` on `Client`.

**Comment by jeremychone** [comment]
Ok, I am sorry, but this commit has way too many changes for me to review. I am swamped right now. 

let me see if I can do it.

**Comment by jeremychone** [comment]
Alright, I've made the commit referenced above #[77cedfb](https://github.com/jeremychone/rust-httpc-test/commit/77cedfb0725b46a5868bda2f3c5013f32915d614), which should address the issue.

- The `.client_store(&self)` method now returns a clone of the `Arc<CookieStoreMutex>`, which is the desired behavior.
- I also added the `.reqwest_client(&self)` method that returns a reference to `&reqwest::Client`, enabling most operations.

Thanks again for the feedback. These changes will be beneficial.

**Pull request closed without merging**
